tut_poll/poll/urls.py
from django.urls import path
from .views import IndexView, DetailView, ResultsView, vote

app_name = 'polls'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>', DetailView.as_view(), name='details'),
    path('<int:pk>/results', ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote', vote, name='vote'),
]

tut_poll/tut_polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tut_polls/', include('poll.urls'))
]

tut_poll/poll/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=256)
    pub_date = models.DateTimeField()

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

tut_poll/poll/views.py
import logging

from django.db.models import F
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice

logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    """
        view to show the list of all the questions present for the poll.
    """

    template_name = 'index.html'
    context_object_name = 'questions'

    def get_queryset(self):
        """
            queryset for IndexView
        :return:
            questions which are published in the past
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')


class DetailView(generic.DetailView):
    """
        view to show the details and options for the questions to vote
    """
    model = Question
    template_name = 'detail.html'


class ResultsView(generic.DetailView):
    """
        view to show the results for the questions.
    """
    model = Question
    template_name = 'result.html'


def vote(request, question_id):
    """
    view to vote on the question
    :param request: request body
    :param question_id: pk of the question
    :return: redirects to results
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist) :
        return render(
            request,
            'detail.html',
            {
                'question': question,
                'error_message': 'you have not selected any choice',
            }
        )
    else:
        selected_choice.vote = F('vote')+1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

tut_poll/templates/poll/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id = "choice{{ forloop.counter }}" value = {{ choice.id }} >
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

tut_poll/templates/poll/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'poll/style.css' %}">

{% if questions %}
    {% for question in questions %}
        <li>
            <a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a>
        </li>
    {% endfor %}
{% else %}
    <p>No polls are available</p>
{% endif %}

tut_poll/templates/poll/result.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>
        {{ choice.choice_text }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}">Vote again?</a>

<a href="{% url 'polls:index' %}">Back to questions</a>